# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git Checkout Code
      uses: actions/checkout@v2
      id: git_checkout

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Build image
      run: docker build . --file Dockerfile --tag springboot-actions-test

    - name: Login registry
      run: echo "${{ secrets.DOCKERHUB_PASSWD }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin

    - name: Push image
      run: |
        IMAGE_ID=xwzj01ht/springboot-actions-test
        echo "HELLO"
        echo IMAGE_ID=$IMAGE_ID
        VERSION=`date "+%Y%m%d"`
        docker tag springboot-actions-test $IMAGE_ID:$VERSION
        docker push $IMAGE_ID:$VERSION
